<template>
  <NuxtPage />
</template>
<script>
import aboutSection from "./components/about-section.vue";
import ServicesSection from "./components/services-section.vue";
export default {
  components: { aboutSection, ServicesSection },
  mounted() {
    var header = document.getElementById("header");
    var hero = document.getElementById("hero");
    var heroBody = document.getElementById("hero-body");
    var heroImage = document.getElementById("hero-image");

    window.onscroll = function (e) {
      var newsy = this.scrollY;
      var oldsy = this.oldScroll;
      // console.log(this.oldScroll > this.scrollY);
      if (oldsy > newsy) {
        // scroll Up

        header.style.top = `-${newsy * 0.2}px`;
        // console.log(`UP new =  ${newsy}\nUP old = ${oldsy}\n\n`);
        if (newsy < 250) {
          heroBody.classList.remove("scale-out-center");
          heroBody.classList.add("scale-up-center");
          header.style.top = `-${newsy * 0.2}px`;
        }
      } else {
        // scroll Down

        // header.style.top = `-${newsy * 0.1}px`;
        // console.log(`DOWN new =  ${newsy}\nDOWN old = ${oldsy}\n\n`);
        if (newsy > 350) {
          heroBody.classList.remove("scale-up-center");
          heroBody.classList.add("scale-out-center");
          header.style.top = `-${newsy * 0.2}px`;
        }
      }
      this.oldScroll = this.scrollY;
    };
    // window.addEventListener("scroll", (e) => {
    //   console.log(e)
    //   console.log('scroll now = ',window.scrollY);
    //

    // });
  },
  head() {
    return {
      title: "Flex Profile",
      link: [
        {
          href: "https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css",
          rel: "stylesheet",
          integrity:
            "sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT",
          crossorigin: "anonymous",
        },
        {
          rel: "stylesheet",
          href: "https://unpkg.com/intl-tel-input@17.0.18/build/css/intlTelInput.min.css",
        },
      ],
      script: [
        {
          src: "https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js",
          integrity:
            "sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8",
          crossorigin: "anonymous",
        },
      ],
    };
  },
};
</script>
<style>
@import url("https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap");
@import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css");
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap");

.arch {
  font-family: "Archivo Black", sans-serif;
}
.sans {
  font-family: "Open Sans", sans-serif;
}
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
:root {
  --dark-plus: #0d1b2a;
  --dark-lite: #1b263b;

  --text-plus: #415a77;
  --text-lite: #778da9;

  --grey: #e5e5e5;

  --hero-body-size: calc(100%);
  --header-size: 150px;

  --color-default: #364d59;
  --color-primary: #1d3557;
  --color-secondary: #52565e;
}
.w-fit {
  width: fit-content;
}
.z-10 {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 10;
}
.point {
  cursor: pointer;
}
.bg-glass {
  /* From https://css.glass */
  background: rgba(0, 0, 0, 0.8);
  box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
  backdrop-filter: blur(5px);
  -webkit-backdrop-filter: blur(5px);
  border: 1px solid rgba(0, 0, 0, 0.05);
}
.hvr-black:hover {
  background-color: var(--dark-plus);
  color: var(--grey);
}
.bg-grey {
  background-color: var(--grey);
}
.text-plus {
  color: var(--text-plus);
}
.text-lite {
  color: var(--text-lite);
}
.text-grey {
  color: var(--grey);
}
.ls-2 {
  letter-spacing: 2px;
}

a {
  color: inherit;
  text-decoration: none !important;
  padding: 0.5rem;
  transition: 0.3s;
}
a:hover{
  color: inherit;
}
/* width */
::-webkit-scrollbar {
  width: 5px;
}

/* Track */
::-webkit-scrollbar-track {
  background: transparent !important;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #888;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: crimson;
}

.w-30 {
  width: 30%;
}
.scale-out-center {
  -webkit-animation: scale-out-center 0.3s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
  animation: scale-out-center 0.3s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-10-11 1:44:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-out-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-out-center {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 1;
  }
}
@keyframes scale-out-center {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(0);
    transform: scale(0);
    opacity: 1;
  }
}

.scale-up-center {
  -webkit-animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1)
    both;
  animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-10-11 9:48:19
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

</style>